### ISSUE TITLE
How to reset the counter from the Stream Deck hardware?

### ISSUE THREAD

**Issue by coreyog** [elgatosf/streamdeck-counter#1]
I installed the counter and tested it out but the only way I found to reset the counter is to remove it and re-add it.

Is there a way to reset the counter from the Stream Deck hardware without interacting with the Stream Deck software?

Press and hold appears to do nothing.

**Comment by tiptronic** [comment]
No - the counter is just an example how to create a plugin.

**Comment by Timac** [comment]
@coreyog Counter 1.3 is now available (and will soon be available directly in the Stream Deck store). It adds the possibility to reset the counter by holding the key pressed for 1.5s.
