### ISSUE TITLE
Is this meant to just be a action for Stream Deck?

### ISSUE THREAD

**Issue by shadromero** [elgatosf/streamdeck-counter#3]
I'm a bit new and confused to this action. Is the Counter add-on an action that can be added to a broadcasting software i.e. OBS to use as overlays or text file implementation? I am wanting to use the counter as a way to count on my live streams but I can find a way to do this with OBS and this stream deck action. Help?

**Comment by Timac** [comment]
This repository contains the **source code of the Counter action**. In the Stream Deck application, you can open the store by clicking on the '_More Actions..._' and locate this _Counter_ action and install it with one click. However this action is not what you are looking for: it only increments a counter displayed on the key when you press the key.

If you are looking for an action to display an overlay in OBS from a text file, you should look at the **OBS Tools** plugin which can be downloaded from the store directly inside the Stream Deck application.
