### ISSUE TITLE
Basically does not work

### ISSUE THREAD

**Issue by Lewiscowles1986** [elgatosf/streamdeck-counter#6]
Downloaded the plugin. Dropped onto StreamDeck Icons, press button. Nada, zilch!

Restarted StreamDeck... Nada, Zilch!

**Comment by enavarrocu** [comment]
@Lewiscowles1986 it does, you need to activate the title for that button.

**Comment by ChekTek** [comment]
I'm not able to reproduce this. Installing by double clicking the `com.elgato.counter.streamDeckPlugin` file seems to work fine. If you are are manually adding the plugin files, you'll want to add it to the plugins folder rather than the icons folder.

**Comment by Lewiscowles1986** [comment]
I installed via the streamdeck app. I've retried since. I Don't know why it's working for you, but this should be removed from the store / download gallery for streamdeck
